version: '3.9'

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - '5432:5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050

    ports:
      - '5050:5050'

  # can be used to run python script on docker

  # password-app:
  #   build: .
  #   container_name: password-app
  #   command: sh -c "sleep 10s ; python3 ./app/main.py"
  #   ports:
  #     - 8080:8080
  #   links:
  #     - postgres
  # stdin_open: true # docker run -i
  # tty: true # docker run -t

volumes:
  postgres-data:
